import ContactForm from "../components/ContactForm";
import { Container, Col, Row } from 'react-bootstrap';

export const metadata = {
    title: 'Dsunstrumfit - Contact',
    description: 'Generated by create next app',
};


export default function Contact() {
    return (
        <Container className="mt-5 contact-container">
            <ContactForm />
        </Container>
    );
}