import { FaFacebook, FaTwitter, FaInstagram, FaDumbbell } from 'react-icons/fa';
import { IoBarbellOutline } from "react-icons/io5";

import Image from 'next/image';
import Link from 'next/link';
import profilePic from "../../public/images/landing-small.jpg";
import { Container, Row, Col } from 'react-bootstrap';

export const metadata = {
    title: 'Dsunstrumfit - Coaching',
    description: 'Generated by create next app',
};


export default function Coaching() {
    return (
        <Container className="mt-5 coaching-container">
            <div className="text-center ">
                <h1 className="section-heading">Coaching</h1>
                <h4 className="section-subheading">Checkout my online training packages</h4>
            </div>

            <Row className="my-4">
                <Col md={{ span: 8, order: 1 }} xs={{ order: 1 }}>
                    <h3 className="section-heading-small">Online Fitness Coaching</h3>
                    <p>
                        Our Online Fitness Coaching program is designed to help you achieve your fitness goals
                        with personalized workout plans, regular check-ins, and expert guidance from our
                        certified trainers. Whether you are looking to lose weight, build muscle, or improve
                        your overall fitness, our program is tailored to meet your individual needs.
                    </p>
                    <div className="price-tag">
                        <span>$149/month</span>
                    </div>
                    <Link href="/contact">
                        <span className="btn-flip" data-back="Contact Me" data-front="Sign Up Today"></span>
                    </Link>
                </Col>
                <Col md={{ span: 4, order: 2 }} xs={{ order: 2 }}>
                    <div className="masked-image">
                        <Image
                            src={profilePic}
                            alt="Online Fitness Coaching"
                            width={400}
                            height={400}
                            className="clientImage img-fluid"
                        />
                    </div>
                </Col>
            </Row>

            {/* Online Nutrition Coaching */}
            <Row className="my-4">
                <Col md={{ span: 4, order: 1 }} xs={{ order: 2 }}>
                    <div className="masked-image">
                        <Image
                            src={profilePic}
                            alt="Online Nutrition Coaching"
                            width={400}
                            height={400}
                            className="clientImage img-fluid"
                        />
                    </div>
                </Col>
                <Col md={{ span: 8, order: 2 }} xs={{ order: 1 }}>
                    <h3 className="section-heading-small">Online Nutrition Coaching</h3>
                    <p>
                        Our Online Nutrition Coaching program offers customized meal plans, nutritional
                        education, and support from our registered dietitians. We will work with you to develop
                        healthy eating habits and create a balanced diet that aligns with your lifestyle and
                        goals. Whether you need help with weight management, sports nutrition, or general
                        wellness, we are here to guide you every step of the way.
                    </p>
                    <div className="price-tag">
                        <span>$149/month</span>
                    </div>
                    <Link href="/contact">
                        <span className="btn-flip" data-back="Contact Me" data-front="Sign Up Today"></span>
                    </Link>
                </Col>
            </Row>

            {/* Online Fitness + Nutrition Coaching */}
            <Row className="my-4" >

                <Col md={{ span: 8, order: 1 }} xs={{ order: 1 }}>
                    <h3 className="section-heading-small">Online Fitness + Nutrition Coaching</h3>
                    <p>
                        Our combined Online Fitness + Nutrition Coaching program provides a holistic approach
                        to health and wellness. You will receive personalized workout plans, tailored meal
                        plans, and continuous support from both our fitness trainers and nutrition experts.
                        This integrated program is perfect for those who want to achieve comprehensive health
                        goals and maintain a balanced lifestyle.
                    </p>
                    <div className="price-tag">
                        <span>$149/month</span>
                    </div>
                    <Link href="/contact">
                        <span className="btn-flip" data-back="Contact Me" data-front="Sign Up Today"></span>
                    </Link>
                </Col>
                <Col md={{ span: 4, order: 2 }} xs={{ order: 2 }}>
                    <div className="masked-image">
                        <Image
                            src={profilePic}
                            alt="Online Fitness + Nutrition Coaching"
                            width={400}
                            height={400}
                            className="clientImage img-fluid"
                        />
                    </div>
                </Col>
            </Row>
        </Container>
    );
}