export const metadata = {
    title: 'Dsunstrumfit - Coaching',
    description: 'Generated by create next app',
};


export default function Coaching() {
    return (
        <div>
            <h1>COACHING</h1>
            <p>This is the Coaching page.</p>
        </div>
    );
}