import { Work_Sans } from "next/font/google";
import "./globals.css";
import CustomNavbar from './components/CustomNavbar';
import CustomFooter from "./components/CustomFooter";
import "./navbar.css";
import "./home.css";
import "./buttons.css";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Dsunstrumfit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={workSans.className}>
        <CustomNavbar />
        <main>{children}</main>
        <CustomFooter />
      </body>
    </html>
  );
}
