import Image from 'next/image';

export const metadata = {
  title: 'DsunstrumFit - Home',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div className="landing">
      <Image
        src="/images/landing-temp.jpg"
        alt="Background Image"
        layout="fill"
        objectFit="cover"
        quality={100}
      />
      <div className="overlay">
        <div className="container text-center">
          <h1>Welcome to DsunstrumFit</h1>
          <p>This is the landing page.</p>
        </div>
      </div>
    </div>
  );
}