import Image from "next/image";

export const metadata = {
  title: 'Grant MacMillan - Home',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div>
      <h1>Welcome to DsunstrumFit</h1>
      <p>This is the landing page.</p>
    </div>
  );
}