export const metadata = {
    title: 'Dsunstrumfit - About Me',
    description: 'Generated by create next app',
};


export default function About() {
    return (
        <div>
            <h1>About Me</h1>
            <p>This is the about me page.</p>
        </div>
    );
}