import { FaFacebook, FaTwitter, FaInstagram, FaDumbbell } from 'react-icons/fa';
import { IoBarbellOutline } from "react-icons/io5";

import Image from 'next/image';
import profilePic from "../../public/images/landing-small.jpg";
import { Container, Row, Col } from 'react-bootstrap';

export const metadata = {
    title: 'Dsunstrumfit - About Me',
    description: 'Generated by create next app',
};

export default function About() {
    return (
        <Container className="mt-5 about-me-container">
            <Row>
                <Col md={4} className="text-center">
                    <div className="masked-image">
                        <Image
                            src={profilePic} // Replace with the actual path to the client's image
                            alt="Client Image"
                            width={400}
                            height={400}
                            className="clientImage img-fluid"
                        />
                    </div>
                    <div className="about-social-icons mb-3">
                        <a href="https://instagram.com" aria-label="Instagram" target="_blank" rel="noopener noreferrer">
                            <FaInstagram size={40} className="icon-style" />
                        </a>
                        <a href="https://twitter.com" className="mx-3" aria-label="Twitter" target="_blank" rel="noopener noreferrer">
                            <FaTwitter size={40} className="icon-style" />
                        </a>
                        <a href="https://facebook.com" aria-label="Facebook" target="_blank" rel="noopener noreferrer">
                            <FaFacebook size={40} className="icon-style" />
                        </a>
                    </div>
                    <p><span className="email-highlight">Email:</span> dylan@example.com</p>
                </Col>
                <Col md={8} >
                    <h1 className='section-heading'>About Me</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim. Cras
                        feugiat malesuada orci, sit amet lacinia nulla ultricies et. Praesent sit amet felis
                        nunc. Nam euismod, tortor non sagittis volutpat, erat leo lobortis metus, a tincidunt
                        turpis eros non eros. Curabitur consequat aliquam metus, at sollicitudin libero euismod
                        et.
                    </p>
                    <Row>
                        <Col md={6}>
                            <h3 className='about-subheading'>Training</h3>
                            <ul className='custom-bullets'>
                                <li>
                                    <IoBarbellOutline className='bullet-icon' /> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                </li>
                                <li>
                                    <IoBarbellOutline className='bullet-icon' /> Nullam in venenatis enim.
                                </li>
                                <li>
                                    <IoBarbellOutline className='bullet-icon' /> Cras feugiat malesuada orci.
                                </li>
                                <li>
                                    <IoBarbellOutline className='bullet-icon' /> Sit amet lacinia nulla ultricies et.
                                </li>
                            </ul>
                        </Col>
                        <Col md={6}>
                            <h3 className='about-subheading'>Certifications</h3>
                            <ul className='custom-bullets'>
                                <li>
                                    <IoBarbellOutline className='bullet-icon' /> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                </li>
                                <li>
                                    <IoBarbellOutline className='bullet-icon' /> Nullam in venenatis enim.
                                </li>
                                <li>
                                    <IoBarbellOutline className='bullet-icon' /> Cras feugiat malesuada orci.
                                </li>
                                <li>
                                    <IoBarbellOutline className='bullet-icon' /> Sit amet lacinia nulla ultricies et.
                                </li>
                            </ul>
                        </Col>
                    </Row>
                </Col>
            </Row>
        </Container>
    );
}